"""Pull every free, licence-clean Korean corpus the 2026-09-11 source sweep cleared, onto the Modal volume.
Each fetch appends a line to /vol/corpora/PROVENANCE.md with the licence as stated at the source.

  wikimedia   kowiki, kowikisource, kowiktionary, kowikibooks dumps (CC BY-SA 4.0)      -> corpora/wikimedia
  hf_text     Hub text sets with verified permissive licences                            -> corpora/hf/<repo>
  hf_vision   Hub Korean document/vision sets with verified permissive licences          -> corpora/hf/<repo>
  law         국가법령정보 open API bulk (statutes, precedents; 저작권법 제7조: not protected) -> corpora/law

Excluded on purpose: AI-Hub (in-zone only), 나무위키 (CC BY-NC-SA), anything tagged NC/ND, anything generated by a
closed model (korean_textbooks and its descendants), the KVQA licence, and licence-stripped mirrors.

    modal deploy harness/fetch_open_korean.py
    .venv/bin/python harness/spawn.py songgot-open wikimedia
    .venv/bin/python harness/spawn.py songgot-open hf_text
    .venv/bin/python harness/spawn.py songgot-open hf_vision
"""
import os
import subprocess
import time

import modal

app = modal.App("songgot-open")
vol = modal.Volume.from_name("songgot", create_if_missing=True)
V = "/vol"
image = modal.Image.debian_slim(python_version="3.11").apt_install("curl", "bzip2").pip_install("huggingface_hub[hf_transfer]", "pyarrow").env({"HF_HUB_ENABLE_HF_TRANSFER": "1"})

WIKIMEDIA = {  # dump name -> licence
    "kowiki": "CC BY-SA 4.0", "kowikisource": "CC BY-SA 4.0 (texts largely public domain)", "kowiktionary": "CC BY-SA 4.0", "kowikibooks": "CC BY-SA 4.0"}
HF_TEXT = {  # repo -> licence as verified on the card on 2026-09-11
    "nvidia/Nemotron-Personas-Korea": "CC BY 4.0 (card); 1M synthetic Korean persona texts",
    "joonhok-exo-ai/korean_law_open_data_precedents": "openrail (card); Korean court decisions from 법제처 open data (not copyright-protected)",
    "etri-lirs/KoTSQA-v.2.0": "CC BY-SA 4.0 (card); ETRI Korean technical QA",
    "CarrotAI/ko-instruction-dataset": "Apache 2.0 (card); WizardLM-2 open teacher",
    "klue/klue": "CC BY-SA 4.0 (card)",
    "devngho/korean-wikipedia-edu": "CC BY-SA 4.0 (card); edu-scored kowiki",
    "heegyu/kowikitext": "CC BY-SA 3.0 (card)",
    "HAERAE-HUB/HAE-RAE-COT-1.5M": "CC BY 4.0 (card); generator undisclosed, keep out of the shipped mix until confirmed",
    "OLAIR/Open-R1-Ko-SFT-v2.0": "MIT (card); DeepSeek-R1 lineage",
    "huggingface-KREW/korean-role-playing": "Apache 2.0 (card)",
    "HAERAE-HUB/HAE_RAE_BENCH_2.0": "MIT (card); eval only",
    "HAERAE-HUB/NOLLI": "MIT (card); eval only",
    "ONTHEIT/KDoc-OCRBench-V2": "CC BY 4.0 (card); eval only",
    "HAERAE-HUB/HAERAE-VISION": "CC BY 4.0 (card); 653 Korean VQA items",
}
HF_VISION = {
    "SamsungSDS-Research/SDS-KoPub-VDR-Benchmark": "CC BY-SA 4.0 (card); 9,180 Korean public-document page images",
    "WueNLP/Synthdog-Multilingual-100": "Apache 2.0 (card); SynthDoG render, Korean among 100 languages",
    "naver-clova-ix/synthdog-ko": "no licence field on the card; upstream Donut repo MIT; 65k synthetic Korean document images. Confirm before shipping weights trained on it",
    "HumynLabs/Korean_Receipts_Dataset": "CC BY 4.0 (card); 20 receipts",
    "HumynLabs/Korean_User_Manuals_Dataset": "CC BY 4.0 (card)",
    "HumynLabs/Korean_Menus_Image_Dataset": "CC BY 4.0 (card)",
    "HumynLabs/Korean-Signs_Image_Dataset": "CC BY 4.0 (card)",
    "HumynLabs/Korean_Price_Tags_Image_Dataset": "CC BY 4.0 (card)",
    "HumynLabs/Korean_Product_Labels_Image_Dataset": "CC BY 4.0 (card)",
}


def note(line: str):
    os.makedirs(f"{V}/corpora", exist_ok=True)
    with open(f"{V}/corpora/PROVENANCE.md", "a", encoding="utf-8") as f:
        f.write(time.strftime("%F %T ") + line + "\n")
    print(line, flush=True); vol.commit()


def dsize(path):
    return sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(path) for f in fs) if os.path.isdir(path) else 0


@app.function(image=image, volumes={V: vol}, cpu=4, memory=16384, timeout=60 * 60 * 4)
def wikimedia():
    out = f"{V}/corpora/wikimedia"; os.makedirs(out, exist_ok=True); t0 = time.time()
    for name, lic in WIKIMEDIA.items():
        url = f"https://dumps.wikimedia.org/{name}/latest/{name}-latest-pages-articles.xml.bz2"; dst = f"{out}/{name}-latest-pages-articles.xml.bz2"
        rc = subprocess.run(["curl", "-sS", "-L", "-C", "-", "--retry", "5", "-o", dst, url]).returncode
        note(f"wikimedia {name}: {lic}; {os.path.getsize(dst)/2**20:.0f} MiB, curl rc={rc}, {url}")
    vol.commit(); note(f"wikimedia DONE in {time.time()-t0:.0f}s")


def _snap(repos: dict, sub: str):
    from huggingface_hub import snapshot_download
    for repo, lic in repos.items():
        t0 = time.time(); dst = f"{V}/corpora/hf/{repo.replace('/', '__')}"
        try:
            snapshot_download(repo, repo_type="dataset", local_dir=dst)
            note(f"hf {repo}: {lic}; {dsize(dst)/2**20:.0f} MiB in {time.time()-t0:.0f}s")
        except Exception as e:
            note(f"hf {repo}: FAILED {type(e).__name__}: {str(e)[:120]}")
    vol.commit()


@app.function(image=image, volumes={V: vol}, cpu=8, memory=32768, timeout=60 * 60 * 6, ephemeral_disk=524288)
def hf_text():
    _snap(HF_TEXT, "text"); note("hf_text DONE")


@app.function(image=image, volumes={V: vol}, cpu=8, memory=32768, timeout=60 * 60 * 6, ephemeral_disk=524288)
def hf_vision():
    _snap(HF_VISION, "vision"); note("hf_vision DONE")


@app.function(image=image, volumes={V: vol}, cpu=4, memory=16384, timeout=60 * 60 * 2, ephemeral_disk=524288)
def hf_one(repo: str, lic: str = "see card"):
    """Fetch one Hub dataset with its licence line recorded in PROVENANCE.md."""
    _snap({repo: lic}, "one"); note(f"hf_one {repo} DONE")
